allowBuilds:
  esbuild: false
  workerd: true
minimumReleaseAgeExclude:
  - '@iconify-json/material-symbols@1.2.88'
  - '@iconify-json/mingcute@1.2.8'
  - '@napi-rs/wasm-runtime@1.2.2'
  - miniflare@5.20260730.0-alpha
  - wrangler@4.118.0
